### ISSUE TITLE
Fix missing report_dir field in NetFlow PCAP test Config initializers

### ISSUE THREAD

**Issue by sehkone** [aicers/reproduce#814]
## Summary

The CI on main is failing due to a compilation error introduced in commit c3977e6 ("Add NetFlow PCAP tests").

The `Config` struct gained a `report_dir: Option<PathBuf>` field in commit 2740af2 ("Enforce report_dir for report output"), but the 4 new `Config` initializers added in the subsequent NetFlow PCAP tests commit do not include this field.

## Error

```
error[E0063]: missing field `report_dir` in initializer of `config::Config`
    --> src/producer.rs:3590:22
     |
3590 |         let config = Config {
     |                      ^^^^^^ missing `report_dir`
```

Same error at lines 3785, 3855, and 3912.

## Fix

Add `report_dir: None` to all 4 `Config` initializers in the new NetFlow test functions.
